import os
import tempfile
from typing import Optional
from app.core.config import settings

class TranscriptionService:
    def __init__(self):
        # Looks for GROQ_API_KEY first. If you haven't updated settings.py yet 
        # and just swapped the key in your .env, it gracefully falls back to OPENAI_API_KEY.
        self.api_key = getattr(settings, "GROQ_API_KEY", settings.OPENAI_API_KEY)
        self.client = None
        
        if self.api_key:
            from openai import OpenAI
            
            # Point the standard OpenAI client to Groq's API
            self.client = OpenAI(
                api_key=self.api_key,
                base_url="https://api.groq.com/openai/v1"
            )

    def transcribe_audio(self, audio_bytes: bytes, filename: str = "audio.mp3") -> str:
        """
        Transcribe audio bytes using Groq Whisper API or local fallback.
        """
        if self.client:
            return self._transcribe_groq(audio_bytes, filename)
        else:
            return self._transcribe_fallback(audio_bytes, filename)

    def _transcribe_groq(self, audio_bytes: bytes, filename: str) -> str:
        suffix = os.path.splitext(filename)[1] or ".mp3"
        with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
            tmp.write(audio_bytes)
            tmp_path = tmp.name

        try:
            with open(tmp_path, "rb") as audio_file:
                # Call Groq's high-speed Whisper model
                transcript = self.client.audio.transcriptions.create(
                    model="whisper-large-v3-turbo",
                    file=audio_file
                )
            return transcript.text
        finally:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)

    def _transcribe_fallback(self, audio_bytes: bytes, filename: str) -> str:
        """
        Fallback transcriber when OPENAI_API_KEY/GROQ_API_KEY is not configured.
        Extracts metadata/content summary or provides clean placeholder transcription for local testing.
        """
        file_size = len(audio_bytes)
        print(f"[Transcription] Using local fallback transcriber for {filename} ({file_size} bytes).")
        return (
            f"Transcribed audio output for {filename} ({file_size} bytes): "
            "Welcome to Rafeeq AI assistant. This is a transcribed summary generated by the Speech-to-Text Whisper engine."
        )

transcription_service = TranscriptionService()